// Contenus de l’audit Wharf. Les médias et les réalisations restent gérés dans Strapi.
export const positioning = 'Agence de stratégie, contenus & production vidéo B2B';
export const description = 'Wharf accompagne la communication corporate des entreprises B2B, de la stratégie éditoriale aux contenus et à la production vidéo.';
export const pageSeo = {
  home: { title: 'Wharf — Stratégie, contenus & production vidéo B2B', description },
  we: { title: 'WE — Le design narratif, méthode Wharf', description: 'Du constat à la création : découvrez comment le design narratif relie stratégie, contenus et vidéo à la réalité de votre entreprise.' },
  work: { title: 'WORK — Stratégie, contenus & vidéo B2B | Wharf', description: 'Stratégie éditoriale, contenus B2B, production vidéo et création d’images et de films par l’IA : découvrez les expertises Wharf.' },
  you: { title: 'YOU — Vos enjeux de communication B2B | Wharf', description: 'Visibilité, parole dirigeante, recrutement, transformation, réseaux sociaux ou film corporate : partons de votre besoin.' },
  contact: { title: 'Contact — Parlons de votre projet | Wharf', description: 'Échangeons sur votre projet de communication B2B : stratégie, contenus, production vidéo ou création d’images et de films par l’IA.' },
  insights: { title: 'INSIGHTS — Stratégie, contenus & vidéo B2B | Wharf', description: 'Guides et analyses Wharf sur la stratégie éditoriale, les contenus, la vidéo, la communication corporate et les enjeux de visibilité B2B.' },
};
export const offers = [
  { id: 'strategy', name: 'STRATEGY', title: 'Donner une direction à votre communication', description: 'Clarifier ce que votre entreprise veut faire comprendre, à qui et pourquoi. Le design narratif relie votre réalité aux messages que vous portez.', items: ['Communication corporate', 'Plateforme narrative', 'Stratégie éditoriale', 'Marque employeur', 'Communication du changement', 'Prise de parole dirigeant'] },
  { id: 'content', name: 'CONTENT', title: 'Donner du fond à vos prises de parole', description: 'Concevoir et rédiger les contenus qui expliquent votre activité, valorisent vos expertises et nourrissent le dialogue avec vos publics. Articles, publications, contenus web et audio : une même exigence éditoriale, en communication interne comme externe.', items: ['Articles, dossiers et livres blancs', 'Magazines, newsletters et rapports d’activité', 'Contenus de sites et pages d’expertise', 'Cas clients, interviews et portraits', 'Tribunes et prises de parole dirigeantes', 'Podcasts et récits audio', 'Adaptations pour les réseaux sociaux'] },
  { id: 'video', name: 'VIDEO', title: 'Donner corps à votre récit', description: 'Concevoir et produire les images qui incarnent votre entreprise, de la préparation du tournage à la postproduction et aux formats de diffusion.', items: ['Film corporate et film de marque', 'Interview dirigeant', 'Portrait collaborateur', 'Série vidéo', 'Motion design', 'Social video et captation'] },
  { id: 'creation-ia', name: 'CRÉATION IA', title: 'Création d’images et de films par l’IA', description: 'Imaginer un univers, choisir un style, donner vie à un scénario. Wharf associe direction artistique et intelligence artificielle pour créer vos images et vos films, du concept au montage final. Une liberté de création élargie, au service de votre récit et de votre identité.', items: ['Concept, scénario et direction artistique', 'Création d’images et d’univers visuels', 'Animation et production vidéo IA', 'Voix-off, musique et création sonore', 'Montage, finitions et déclinaisons', 'Films de marque, contenus de campagne et formats courts', 'Création générative ou production hybride avec tournage'] },
];
export const situations = [
  { id: 'visibilite', titre: 'Faire connaître votre entreprise', description: 'Votre expertise mérite d’être mieux comprise. Clarifions votre message et les preuves qui aideront vos publics à reconnaître votre valeur.', formats: 'Communication corporate, stratégie éditoriale, contenus B2B.', links: [{ label: 'Clarifier votre positionnement', href: '/work#strategy' }, { label: 'Faire vivre votre expertise', href: '/work#content' }], readingSlug: 'cas-client-preuve-expertise' },
  { id: 'dirigeants', titre: 'Donner la parole à vos dirigeants', description: 'Vous avez une vision ou une conviction à partager. Construisons une prise de parole claire, incarnée et adaptée à ceux qui doivent l’entendre.', formats: 'Conseil éditorial, interview, LinkedIn, vidéo.', links: [{ label: 'Préparer la prise de parole', href: '/work#strategy' }, { label: 'Produire une interview', href: '/work#video' }], readingSlug: 'preparer-interview-dirigeant-video' },
  { id: 'recrutement', titre: 'Attirer et recruter', description: 'Faire découvrir vos métiers et votre environnement de travail aide les candidats à se projeter. Partons de la réalité vécue par vos équipes.', formats: 'Marque employeur, témoignages collaborateurs, campagnes vidéo.', links: [{ label: 'Construire la marque employeur', href: '/work#strategy' }, { label: 'Filmer les métiers et les équipes', href: '/work#video' }] },
  { id: 'transformation', titre: 'Expliquer une transformation', description: 'Vos équipes ont besoin de comprendre ce qui change et ce que cela implique. Rendons la transformation concrète et donnons la parole à ceux qui la vivent.', formats: 'Communication interne, récit du changement, films et contenus pédagogiques.', links: [{ label: 'Cadrer le récit du changement', href: '/work#strategy' }, { label: 'Créer les contenus pédagogiques', href: '/work#content' }] },
  { id: 'reseaux', titre: 'Produire régulièrement pour vos réseaux', description: 'Vous souhaitez prendre la parole dans la durée. Organisons les sujets, les tournages et les déclinaisons autour de vos priorités éditoriales.', formats: 'Stratégie social media, journées de tournage, séries vidéo, déclinaisons.', links: [{ label: 'Organiser les contenus', href: '/work#content' }, { label: 'Produire une série vidéo', href: '/work#video' }], readingSlug: 'tournage-videos-articles-linkedin' },
  { id: 'film', titre: 'Produire un film', description: 'Vous avez un sujet, une échéance ou un brief. Définissons le parti pris, les moyens et les formats nécessaires pour lui donner forme.', formats: 'Conception, réalisation, production, postproduction.', links: [{ label: 'Concevoir et produire le film', href: '/work#video' }, { label: 'Explorer la création IA', href: '/work#creation-ia' }] },
];
export const insightTopics = [
  { slug: 'video-b2b', title: 'Vidéo B2B', description: 'Préparer un film, organiser un tournage et choisir les formats de diffusion.', subjects: ['Quels postes font varier le budget d’une vidéo corporate ?', 'Comment préparer une interview dirigeant ?', 'Comment décliner un tournage en plusieurs formats ?'] },
  { slug: 'communication-corporate', title: 'Communication corporate', description: 'Rendre la réalité de l’entreprise compréhensible et construire une parole cohérente.', subjects: ['Comment traduire une transformation en messages concrets ?', 'Comment relier plateforme narrative et prises de parole ?'] },
  { slug: 'content-b2b', title: 'Content B2B', description: 'Faire vivre une expertise à travers une ligne éditoriale et des contenus réguliers.', subjects: ['Comment construire un calendrier éditorial à partir des enjeux clients ?', 'Quels formats préparer pour LinkedIn et YouTube ?'] },
  { slug: 'marque-employeur', title: 'Marque employeur', description: 'Faire découvrir les métiers, les équipes et l’expérience de travail.', subjects: ['Comment préparer un témoignage collaborateur ?', 'Comment montrer la réalité d’un métier en vidéo ?'] },
];
