import { generateMetadataFromStrapi } from '../lib/metadata';
import { WebPageJsonLd } from '../components/JsonLd';
import { AudiencePreferencesButton } from '../components/Measurement';
export const metadata = generateMetadataFromStrapi('Confidentialité et mesure d’audience | Wharf', 'Comment Wharf mesure les visites et protège les informations transmises via son formulaire de contact.', undefined, '/confidentialite');
export default function PrivacyPage() {
  return <main id="main-content" className="engagement-page"><WebPageJsonLd path="/confidentialite" title="Confidentialité et mesure d’audience" description="Comment Wharf mesure les visites et protège les informations transmises via son formulaire de contact." /><div className="engagement-container">
    <div className="engagement-hero"><h1>Confidentialité et mesure d’audience</h1><p>Dernière mise à jour : 6 octobre 2026.</p></div>
    <section className="engagement-section"><h2>La mesure des visites</h2><p>Avec votre accord, Wharf utilise Umami, hébergé sur le même serveur que le site, pour comprendre quelles pages sont consultées et quelles actions sont réalisées : accès à Contact, clic sur un lien email, envoi réussi du formulaire et lecture d’un film du portfolio.</p><p>Les statistiques contiennent l’adresse de la page publique, le domaine du site d’origine, la langue du navigateur, le pays approximatif déduit localement de l’adresse IP et les caractéristiques techniques traitées par Umami. Ni région ni ville ne sont enregistrées. Les paramètres des adresses, les fragments, les adresses email et le texte des formulaires ne sont pas transmis. Les espaces clients et les pages d’administration sont exclus. Aucun enregistrement de session ni suivi entre différents sites n’est activé.</p><p>L’adresse IP reçue par le serveur sert au calcul d’un identifiant pseudonyme dans Umami ; elle n’est pas conservée dans la base de statistiques. La mesure reste donc partielle : les refus, bloqueurs et préférences « Do Not Track » sont respectés.</p></section>
    <section className="engagement-section"><h2>Vos choix et la conservation</h2><p>La mesure ne démarre qu’après acceptation. Votre choix est mémorisé dans votre navigateur pendant six mois ; vous pouvez le modifier à tout moment. Les données détaillées de mesure sont conservées treize mois, puis supprimées. Les synthèses mensuelles agrégées servent au suivi de l’activité du site.</p><AudiencePreferencesButton /></section>
    <section className="engagement-section"><h2>Les demandes de contact</h2><p>Les coordonnées et le message saisis dans le formulaire sont transmis via EmailJS pour permettre à Wharf de répondre à votre demande. Ils ne sont pas associés à un profil de visiteur dans Umami. La qualification des demandes et le suivi des échanges commerciaux sont gérés séparément, dans un espace privé.</p><p>Pour toute question concernant vos informations ou pour exercer vos droits, écrivez à <a href="mailto:contact@bywharf.com">contact@bywharf.com</a>.</p></section>
  </div></main>;
}
